{
    'name': "University Management",
    'version': "18.0.1.0",
    'summary': "Computer Science Department Management System",
    'category': "Education",
    'license': "LGPL-3",
    'depends': ['base','mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/default_batches.xml',
        'views/university_students.xml',
        'views/university_teachers.xml',
        'views/university_subjects.xml',
        'views/university_batch.xml',
        'views/university_lecture.xml',
        'views/university_portal_templates.xml',
        'wizard/university_fees.xml',
        'report/university_students_id_card.xml',
        'report/report_actions.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
}
